name: Test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

# If this workflow is already running on a PR or branch, cancel it.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  TestSDCs:
    name: 'R: Test SDC Parse'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: 'Install Dependencies'
        run: sudo apt update && sudo apt install -y flex bison tcl-dev

      - name: 'Install Python Dependencies'
        run: |
          python3 -m pip install --upgrade pip
          pip install lit filecheck

      - name: 'Run LIT Tests'
        run: |
          cmake -H. -Bbuild -DCMAKE_COMPILE_WARNING_AS_ERROR=on
          cmake --build build/ --target check-libsdcparse
